language: go

go:
  - 1.13.x
  - stable

env: GO111MODULE=on GOFLAGS='-mod vendor'

install: true

before_install: cd V2

before_script:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
    - golangci-lint run
    - go test -v -race ./...